# Generated by Django 5.1.2 on 2024-11-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
