# Generated by Django 5.1.2 on 2024-11-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_categories_options_alter_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='postal_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
