# Generated by Django 5.1.2 on 2024-11-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
