# Generated by Django 5.1.2 on 2024-11-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
